[package]
name = "naglfar"
version = "0.1.2"
authors = ["uint256_t <maekawatoshiki@github.com>"]

[dependencies]
app_units = "0.6.1"
gtk = "*"
gdk = "*"
cairo-rs = "*"
clap = "*"
pango = "*"
pangocairo = "*"
